Repository newrelic/k8s-agents-operator, pull requests merged in 2024-06, with the labels that each got.

#40 refactor: Update inject filename
  src/apm/ruby.go
Labels: Release/other

#45 chore: Skip empty release
  .github/workflows/draft-image-release.yml
Labels: Release/other, Release/skip

#29 feat: Add pullPolicy to values in Helm charts
  charts/k8s-agents-operator/templates/deployment.yaml
  charts/k8s-agents-operator/values.yaml
Labels: Release/feat

#46 docs: Update chart's `README.md`
  charts/k8s-agents-operator/README.md.gotmpl
Labels: Release/other

#47 chore: Add demo apps for E2E testing
  tests/e2e/apps/dotnet_deployment.yaml
  tests/e2e/apps/java_deployment.yaml
  tests/e2e/apps/nodejs_deployment.yaml
  tests/e2e/apps/python_deployment.yaml
Labels: Release/other

#49 test: E2E-specific installation values
  tests/e2e/e2e-values.yml
Labels: Release/other

#50 test: E2E-specific instrumentation CRD
  tests/e2e/e2e-instrumentation.yml
Labels: Release/other

#51 test: E2E test script
  tests/e2e/e2e-tests.sh
Labels: Release/other

#52 test: E2E tests documentation
  tests/e2e/README.md
Labels: Release/other

#54 test: Automate E2E tests
  .github/workflows/ci.yml
  tests/e2e/e2e-tests.sh
Labels: Release/other

#55 docs: add agent specific documentation
  charts/k8s-agents-operator/README.md
Labels: Release/other

#56 feat: Lint Go files
  .github/.golangci.yml
  .github/workflows/ci.yml
Labels: Release/feat

#58 docs: Update chart documentation
  charts/k8s-agents-operator/README.md
  charts/k8s-agents-operator/README.md.gotmpl
Labels: Release/other

#57 feat: Lint Helm chart files
  .github/workflows/ci.yml
Labels: Release/feat

#62 feat: Configure Renovate dependency manager
  .github/renovate.json5
Labels: Release/feat

#59 test: Update E2E tests to use APM agents Docker repositories
  tests/e2e/e2e-instrumentation.yml
Labels: Release/other

#65 chore: Fix newline
  charts/k8s-agents-operator/templates/deployment.yaml
Labels: Release/other

#67 chore: Fix newline
  charts/k8s-agents-operator/templates/deployment.yaml
Labels: Release/other

#69 chore: Fix newline
  charts/k8s-agents-operator/templates/certmanager.yaml
Labels: Release/other

#71 feat: Use public Docker repositories
  charts/k8s-agents-operator/README.md
  charts/k8s-agents-operator/README.md.gotmpl
  src/main.go
  tests/e2e/e2e-instrumentation.yml
  tests/kustomize/samples/instrumentation_v1alpha1_instrumentation.yaml
Labels: Release/feat

#73 feat: Security pipeline
  .github/security.yml
Labels: Release/feat
