Repository newrelic/k8s-agents-operator, pull requests merged in 2025-01, with the labels that each got.

#173 fix(php): correct check for first processed container
  src/apm/php.go
Labels: Release/fix

#151 docs(php): add php operator considerations
  charts/k8s-agents-operator/README.md
  charts/k8s-agents-operator/README.md.gotmpl
Labels: Release/other

#165 feat(php): add 8.4 support
  internal/apm/php.go
Labels: Release/feat

#184 fix: add some tests
  api/v1alpha2/instrumentation_conversion_test.go
  cmd/main.go
  internal/instrumentation/health.go
  internal/instrumentation/health_check.go
  internal/instrumentation/health_test.go
  internal/instrumentation/util/worker/workers_test.go
Labels: Release/fix

#183 fix(php): add php 8.4 to `acceptableLangs`
  api/v1beta1/instrumentation_webhook.go
Labels: Release/fix

#194 chore(deps): Update dependencies
  go.mod
  go.sum
Labels: Release/other

#158 fix: Update linter file config
  .github/.golangci.yml
  cmd/main.go
Labels: Release/fix

#207 fix: update env and container for health agent
  api/v1beta1/instrumentation_webhook.go
  go.sum
  internal/apm/dotnet.go
  internal/apm/golang.go
  internal/apm/health.go
  internal/apm/health_test.go
  internal/apm/helper.go
  internal/apm/java.go
  internal/apm/nodejs.go
  internal/apm/php.go
  internal/apm/python.go
  internal/apm/ruby.go
  internal/instrumentation/health_check.go
  internal/instrumentation/util/worker/manyworkers_test.go
  tools/go.mod
  tools/go.sum
Labels: Release/fix
